### ISSUE TITLE
FAILED: Parsing Normals

### ISSUE THREAD

**Issue by Jostiuk** [edunad/qube#3]
## Issue Type

- [Yes ] Model .obj loading
- [ ] Model texture loading

- [Yes ] Entity related
- [ ] Lua error

## Model data (if any)

- URL : https://www.dropbox.com/s/8aegf12dj5lm3fz/testing_custom_thing_again_again.obj?dl=0
- TEXTURE :

**Comment by edunad** [comment]
Sorry it took me a while to look into it!
After importing and exporting on blender I could open it on prop_mesh
Pretty sure 3DMax is doing some weird formatting on obj files :(

![](https://i.rawr.dev/3lLZaGcj3N.png)

**Comment by Jostiuk** [comment]
Ugh thanks. Guess I'll just have to figure out how to get blender working.
